//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_de_fin_de_formation_ahz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Account
    {
        public int AdminID { get; set; }
        public string Email { get; set; }
        public string Password_ { get; set; }
        public string Admin_Name { get; set; }
    }
}
