//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_de_fin_de_formation_ahz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User_Account
    {
        public int UserID { get; set; }
       
        [Required(ErrorMessage = "Enter Your Name ")]
        [Display(Name ="Name")]
        public string UserName { get; set; }
        public string Account_Status { get; set; }

        [Required(ErrorMessage = "Enter Your Email ")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Select Your Country ")]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Enter Your Phone Number ")]
        [Display(Name = "Phone Number")]
        public string Phone_Number { get; set; }

        
        [Required(ErrorMessage = "Enter Your Password ")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password_ { get; set; }
        [Required(ErrorMessage = "Renter Your password ")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("Password_", ErrorMessage = "Password isn't the same, try again")]
        public string RePassword_ { get; set; }

        [Required(ErrorMessage = "Enter Your BirthDate ")]
        [Display(Name = "Birth Date")]
        public Nullable<System.DateTime> Birth_Date { get; set; }


    }
}
